runtime: python39

# Variables de entorno para producci칩n
env_variables:
  ENVIRONMENT: "production"
  DEBUG: "false"

# Configuraci칩n de escalado autom치tico
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Configuraci칩n de recursos
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Handlers
handlers:
- url: /.*
  script: auto
  secure: always

# Tiempo de vida de la instancia
instance_class: F2